const assert=require('node:assert/strict'),R=require('./logic.js'),seed=require('./data.json');let d=structuredClone(seed);
const day='2026-09-05';
for(const p of ['AT','LW','RW'])assert.equal(R.next(d,p,day).item.id,'AT-601','Shared Kiro installation comes first');
const t=id=>d.tasks.find(t=>t.id===id);
function finish(id){for(const dep of t(id).dependencies)finish(dep);t(id).status='done'}
t('AT-601').status='done';
for(const p of ['AT','LW','RW'])assert.match(R.next(d,p,day).item.id,/-(602|631)$/,'Setup continues before project work');
finish('AT-635');
assert.equal(R.next(d,'AT',day).kind,'decision','Architecture decision follows setup');
assert.notEqual(R.next(d,'RW',day).item.id,'RW-101','AT setup does not complete RUNWELL setup');
finish('RW-635');assert.equal(R.next(d,'RW',day).item.id,'RW-101');
finish('LW-635');assert.equal(R.next(d,'LW',day).item.id,'LW-D02');
d.decisions.find(x=>x.id==='LW-D02').status='resolved';assert.equal(R.next(d,'LW',day).item.id,'LW-101');
assert.equal(R.health(d,'AT',day).label,'Blocked');
assert.equal(R.progress(d.tasks).total,d.tasks.filter(t=>t.status!=='deferred').length);
assert.equal(R.lane(d,'RW','2026-10-01'),'Primary · design-partner release');
for(const task of d.tasks)task.status='done';for(const de of d.decisions)de.status='resolved';
assert.equal(R.next(d,'RW').kind,'complete');assert.equal(R.gateDone(d,d.gates[0]),false);
for(const task of d.tasks)task.evidence='Verified';assert.equal(R.health(d,'RW').label,'Complete');
console.log('Setup-first sequencing, separate project gates, decisions, release readiness, and completion tests passed.');
