const assert=require('node:assert/strict'),R=require('./logic.js'),seed=require('./data.json');let d=structuredClone(seed);
const day='2026-09-13',t=id=>d.tasks.find(t=>t.id===id);
function finish(id){for(const dep of t(id).dependencies)finish(dep);t(id).status='done'}
for(const p of ['AT','LW','RW'])assert.equal(R.next(d,p,day).item.id,'AT-601','Installation remains first');
finish('AT-635');assert.equal(R.next(d,'AT',day).item.id,'AT-108','Program recommendation precedes optional demo decisions');
assert.notEqual(R.next(d,'RW',day).item.id,'RW-6006','AT setup is not RW setup');
finish('RW-635');assert.equal(R.next(d,'RW',day).item.id,'RW-101');
finish('LW-635');assert.equal(R.next(d,'LW',day).item.id,'LW-301');
t('LW-301').status='doing';t('LW-301').startDate='2027-01-01';assert.equal(R.next(d,'LW',day).item.id,'LW-301','Doing beats obsolete future start dates');
finish('LW-101');finish('LW-102');finish('LW-103');d.decisions.find(x=>x.id==='LW-D02').status='resolved';const tracks=R.nextByTrack(d,'LW',day);
assert.equal(tracks.find(x=>x.track.id==='core').result.item.id,'LW-301');
assert.equal(tracks.find(x=>x.track.id==='research').result.item.id,'LW-104');
assert.equal(tracks.find(x=>x.track.id==='integration').result.kind,'waiting');
assert.equal(R.progress(d.tasks).total,d.tasks.filter(t=>t.status!=='deferred'&&!t.optional).length);
assert.equal(R.lane(d,'RW','2026-10-01'),R.lane(d,'RW','2026-09-13'),'No automatic October switch');
assert.ok(t('RW-306').dependencies.includes('RW-302'),'Payments gate partner UAT');
for(const id of ['RW-309','RW-310'])assert.ok(t('RW-306').dependencies.includes(id),'Business OS gates partner UAT');
function ancestors(id,seen=new Set()){for(const dep of t(id).dependencies){if(!seen.has(dep)){seen.add(dep);ancestors(dep,seen)}}return seen}
for(const id of ancestors('AT-111'))assert.ok(!t(id).optional,'Recommendation has no demo prerequisite');
for(const id of ['LW-201','LW-202','LW-204','LW-208'])assert.ok(!ancestors('LW-206').has(id),'Ablation independent of production ingest');
assert.ok(ancestors('LW-112').has('LW-110'),'Real acquisition requires access resolution');
assert.ok(!ancestors('LW-111').has('LW-110'),'Synthetic preparation remains independent');
assert.ok(ancestors('LW-201').has('LW-206'),'Production integration follows ablation');
for(const status of ['ready','doing','blocked'])assert.equal(R.overdue({status,targetDate:'2026-09-12'},day),true);
for(const status of ['done','deferred'])assert.equal(R.overdue({status,targetDate:'2026-09-12'},day),false);
for(const date of [null,'','2026-09-13'])assert.equal(R.overdue({status:'ready',targetDate:date},day),false);
for(const task of d.tasks)task.status='done';for(const de of d.decisions)de.status='resolved';
assert.equal(R.next(d,'RW').kind,'complete');assert.equal(R.gateDone(d,d.gates[0]),false);
for(const task of d.tasks)task.evidence='Verified';assert.equal(R.health(d,'RW').label,'Complete');
console.log('Branch recommendations, optional demo, research/production ordering, payment/BOS gates, dates and setup checks passed.');
